name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        env:
          PROBE_DSN: "host=postgres user=postgres dbname=postgres port=5432 password=postgres"
          POSTGRES_PORT: 5432
      - name: Codecov
        uses: codecov/codecov-action@v1